### ISSUE TITLE
Download models using the script Models\download_models.sh

### ISSUE THREAD

**Issue by ashiqimran** [neccam/SubUNets#2]
Can't download the models, ERROR 404

**Comment by neccam** [comment]
Hi,

So sorry for the incredibly late reply. The models are there now. I am planning to write the unified evaluation script asap and release it too.

**Comment by Rhythmblue** [comment]
Hi neccam,
I read the evaluation tool in PHOENIX2014 folder.
There are some simplifications said in that file like，
`remove __LEFTHAND__ and __EPENTHESIS__ and __EMOTION__ from ctm. `
 `remove all words starting and ending with "__"` 
`remove all -PLUSPLUS suffixes.` 
`remove all cl- prefix. `
`remove all loc- prefix. `
`remove RAUM at the end (eg. NORDRAUM -> NORD). `

1. Like this one `remove all loc- prefix`, does it mean `loc-Paris = Paris' during evaluation.
2. looking forward to your evaluation script, so I can test my result with your official eval code and get the right WER.

@neccam

**Comment by neccam** [comment]
Hi Hao Zhou,

I used the same evaluation script provided in the PHOENIX 2014 folder by Koller et al.

What I did was to produce a hypothesis file, which is an output of the network after beam search decoder. Then I fed it directly to the evaluation script which applies the mentioned changes and compares it against the reference files.

**Comment by Rhythmblue** [comment]
Thanks for your quick reply. 
In that script, It need to turn results into the format of ctm. 
I read the description of ctm in website, but there is still a problem.

In example file,
'15December_2009_Tuesday_tagesschau_default-8 1 1.180 0.110 SCHWACH'
They say 1.180 is start time. 0.110 is duration. Could you teach me how to get the float number of start time and duration.

**Comment by Rhythmblue** [comment]
oh, I find the way.
The duration is random number and has no effect to the final result.

Thank you for your help,  neccam!
👍

**Comment by neccam** [comment]
Great to hear! I just checked old my codes. Similar to you, I was just using values starting from 0 with increments of 0.1 for each predicted word.

As you have discovered they have nothing to do with the result as they correspond to the timing information.

**Comment by Sciroccogti** [comment]
Is that to say these lines in README is not valid yet?
https://github.com/neccam/SubUNets/blob/ba2fc19a27e6b10756e28685692a77147b3d9706/README.md#L17
